' Project : Chinese Chess V1
' Programmer : Wong Wei Jian
' Date : 31/01/2011
' Descripitons : Chinese Chess V1

Module ModuleConvertRowColumnToHorNVer
    Public Horizontal, Vertical As String

    Public Sub ChangeToHorVer()
        Select Case (RowColumn)
            Case "a1"
                Horizontal = "a"
                Vertical = "1"
            Case "a2"
                Horizontal = "a"
                Vertical = "2"
            Case "a3"
                Horizontal = "a"
                Vertical = "3"
            Case "a4"
                Horizontal = "a"
                Vertical = "4"
            Case "a5"
                Horizontal = "a"
                Vertical = "5"
            Case "a6"
                Horizontal = "a"
                Vertical = "6"
            Case "a7"
                Horizontal = "a"
                Vertical = "7"
            Case "a8"
                Horizontal = "a"
                Vertical = "8"
            Case "a9"
                Horizontal = "a"
                Vertical = "9"
            Case "a10"
                Horizontal = "a"
                Vertical = "10"
            Case "b1"
                Horizontal = "b"
                Vertical = "1"
            Case "b2"
                Horizontal = "b"
                Vertical = "2"
            Case "b3"
                Horizontal = "b"
                Vertical = "3"
            Case "b4"
                Horizontal = "b"
                Vertical = "4"
            Case "b5"
                Horizontal = "b"
                Vertical = "5"
            Case "b6"
                Horizontal = "b"
                Vertical = "6"
            Case "b7"
                Horizontal = "b"
                Vertical = "7"
            Case "b8"
                Horizontal = "b"
                Vertical = "8"
            Case "b9"
                Horizontal = "b"
                Vertical = "9"
            Case "b10"
                Horizontal = "b"
                Vertical = "10"
            Case "c1"
                Horizontal = "c"
                Vertical = "1"
            Case "c2"
                Horizontal = "c"
                Vertical = "2"
            Case "c3"
                Horizontal = "c"
                Vertical = "3"
            Case "c4"
                Horizontal = "c"
                Vertical = "4"
            Case "c5"
                Horizontal = "c"
                Vertical = "5"
            Case "c6"
                Horizontal = "c"
                Vertical = "6"
            Case "c7"
                Horizontal = "c"
                Vertical = "7"
            Case "c8"
                Horizontal = "c"
                Vertical = "8"
            Case "c9"
                Horizontal = "c"
                Vertical = "9"
            Case "c10"
                Horizontal = "c"
                Vertical = "10"
            Case "d1"
                Horizontal = "d"
                Vertical = "1"
            Case "d2"
                Horizontal = "d"
                Vertical = "2"
            Case "d3"
                Horizontal = "d"
                Vertical = "3"
            Case "d4"
                Horizontal = "d"
                Vertical = "4"
            Case "d5"
                Horizontal = "d"
                Vertical = "5"
            Case "d6"
                Horizontal = "d"
                Vertical = "6"
            Case "d7"
                Horizontal = "d"
                Vertical = "7"
            Case "d8"
                Horizontal = "d"
                Vertical = "8"
            Case "d9"
                Horizontal = "d"
                Vertical = "9"
            Case "d10"
                Horizontal = "d"
                Vertical = "10"
            Case "e1"
                Horizontal = "e"
                Vertical = "1"
            Case "e2"
                Horizontal = "e"
                Vertical = "2"
            Case "e3"
                Horizontal = "e"
                Vertical = "3"
            Case "e4"
                Horizontal = "e"
                Vertical = "4"
            Case "e5"
                Horizontal = "e"
                Vertical = "5"
            Case "e6"
                Horizontal = "e"
                Vertical = "6"
            Case "e7"
                Horizontal = "e"
                Vertical = "7"
            Case "e8"
                Horizontal = "e"
                Vertical = "8"
            Case "e9"
                Horizontal = "e"
                Vertical = "9"
            Case "e10"
                Horizontal = "e"
                Vertical = "10"
            Case "f1"
                Horizontal = "f"
                Vertical = "1"
            Case "f2"
                Horizontal = "f"
                Vertical = "2"
            Case "f3"
                Horizontal = "f"
                Vertical = "3"
            Case "f4"
                Horizontal = "f"
                Vertical = "4"
            Case "f5"
                Horizontal = "f"
                Vertical = "5"
            Case "f6"
                Horizontal = "f"
                Vertical = "6"
            Case "f7"
                Horizontal = "f"
                Vertical = "7"
            Case "f8"
                Horizontal = "f"
                Vertical = "8"
            Case "f9"
                Horizontal = "f"
                Vertical = "9"
            Case "f10"
                Horizontal = "f"
                Vertical = "10"
            Case "g1"
                Horizontal = "g"
                Vertical = "1"
            Case "g2"
                Horizontal = "g"
                Vertical = "2"
            Case "g3"
                Horizontal = "g"
                Vertical = "3"
            Case "g4"
                Horizontal = "g"
                Vertical = "4"
            Case "g5"
                Horizontal = "g"
                Vertical = "5"
            Case "g6"
                Horizontal = "g"
                Vertical = "6"
            Case "g7"
                Horizontal = "g"
                Vertical = "7"
            Case "g8"
                Horizontal = "g"
                Vertical = "8"
            Case "g9"
                Horizontal = "g"
                Vertical = "9"
            Case "g10"
                Horizontal = "g"
                Vertical = "10"
            Case "h1"
                Horizontal = "h"
                Vertical = "1"
            Case "h2"
                Horizontal = "h"
                Vertical = "2"
            Case "h3"
                Horizontal = "h"
                Vertical = "3"
            Case "h4"
                Horizontal = "h"
                Vertical = "4"
            Case "h5"
                Horizontal = "h"
                Vertical = "5"
            Case "h6"
                Horizontal = "h"
                Vertical = "6"
            Case "h7"
                Horizontal = "h"
                Vertical = "7"
            Case "h8"
                Horizontal = "h"
                Vertical = "8"
            Case "h9"
                Horizontal = "h"
                Vertical = "9"
            Case "h10"
                Horizontal = "h"
                Vertical = "10"
            Case "i1"
                Horizontal = "i"
                Vertical = "1"
            Case "i2"
                Horizontal = "i"
                Vertical = "2"
            Case "i3"
                Horizontal = "i"
                Vertical = "3"
            Case "i4"
                Horizontal = "i"
                Vertical = "4"
            Case "i5"
                Horizontal = "i"
                Vertical = "5"
            Case "i6"
                Horizontal = "i"
                Vertical = "6"
            Case "i7"
                Horizontal = "i"
                Vertical = "7"
            Case "i8"
                Horizontal = "i"
                Vertical = "8"
            Case "i9"
                Horizontal = "i"
                Vertical = "9"
            Case "i10"
                Horizontal = "i"
                Vertical = "10"
        End Select
    End Sub
End Module
